### ISSUE TITLE
helpers to do comparison

### ISSUE THREAD

**Issue by iilyak** [davidB/handlebars_misc_helpers#11]
I am very new to handlebars and might be missing something. I am trying to do a conditional inclusion:
```
{{#if var == 123}}
...
{{/if}}
``` 

I couldn't find a way to do comparisons using `#if`. It looks like the `#if` works only with boolean values.
This [gist](https://gist.github.com/pheuter/3515945) (for javascript based implementation of handlebars) suggest registering helper. 

`compare` helper from the above gist might solve the issue:
```
{{#compare "Test" "Test"}}
  Default comparison of "==="
{{/compare}}

{{#compare Database.Tables.Count ">" 5}}
  There are more than 5 tables
{{/compare}}
```

**Comment by sunng87** [comment]
There are some built-in comparison helpers in handlebars-rust:

https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/helper_boolean.rs

And you can create these kind of helpers easily with macro: `handlebars_helper!`

**Comment by davidB** [comment]
You can do
```
{{#if (eq var 123)}}
...
{{/if}}

{{#if (gt var 123)}}
...
{{/if}}

{{#if (lt var 123)}}
...
{{/if}}
```

list of fonction (copy from the link in the comment of sunng87)

```
handlebars_helper!(eq: |x: Json, y: Json| x == y);
handlebars_helper!(ne: |x: Json, y: Json| x != y);
handlebars_helper!(gt: |x: i64, y: i64| x > y);
handlebars_helper!(gte: |x: i64, y: i64| x >= y);
handlebars_helper!(lt: |x: i64, y: i64| x < y);
handlebars_helper!(lte: |x: i64, y: i64| x <= y);
handlebars_helper!(and: |x: Json, y: Json| x.is_truthy(false) && y.is_truthy(false));
handlebars_helper!(or: |x: Json, y: Json| x.is_truthy(false) || y.is_truthy(false));
handlebars_helper!(not: |x: Json| !x.is_truthy(false));
```

**Comment by iilyak** [comment]
feel free to close. Thank you for pointing me to the alternative ways of doing it.

**Comment by davidB** [comment]
Sorry I made a mistake (syntax error), I updated my comment:

`(var eq 123)` => `(eq var 123)` call the function eq with args and return a boolean
