### ISSUE TITLE
`string` feature relies on `serde_json` crate

### ISSUE THREAD

**Issue by mainrs** [davidB/handlebars_misc_helpers#46]
https://github.com/davidB/handlebars_misc_helpers/blob/992c532d8f3799d3695ee961e392e3a0ce6e21d5/src/string_helpers.rs#L29-L39

Compiling with `features = ["string"], default-features = false` fails due to the missing dependency.

**Comment by davidB** [comment]
Thanks for reporting, fixed with 0.15
